### ISSUE TITLE
More Client Info link goes nowhere

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#348] opened 2016-09-24 00:34 UTC
**Summary:** 

More client info link from More Menu goes nowhere
**Steps to reproduce:** 

Click more menu, click more client info
**Expected behavior:** 

Display additional client details
**Observed behavior:** 
Nothing happens
**Device and Android version:** 
Demo3 tenant on HTC One M8 with Android 6.0
**Screenshots:**

**Comment by sosnickm** [comment] 2016-10-23 06:00
When using a different device this doesn't happen for me, could you try and reproduce and see if this still happens? If not, I can try to look into why this happened to you.

**Comment by prathmeshranaut** [comment] 2016-12-09 19:13
**Before** clicking `More Info` on the clients page.
<img width="368" alt="screen shot 2016-12-10 at 12 41 38 am" src="https://cloud.githubusercontent.com/assets/3950603/21061242/7a417598-be71-11e6-80ac-3e8ad3d979e5.png">
**After** clicking the `More Info` button
<img width="367" alt="screen shot 2016-12-10 at 12 41 45 am" src="https://cloud.githubusercontent.com/assets/3950603/21061265/8a0cc9dc-be71-11e6-9d33-d8e196da0ad8.png">
**Device and Android version:**
Android Emulator Nexus 5 with Android 7.1

**Comment by tarun0** [comment] 2017-01-17 12:53
@edcable I too can't see any issue in this either. Could you please elaborate what should be the expected behaviour?

![348](https://cloud.githubusercontent.com/assets/12914286/22021223/f861e60e-dce1-11e6-9108-9cf252f688a6.gif)

**Comment by therajanmaurya** [comment] 2017-01-23 15:39
@edcable You have encountered this issue because whenever we are opening the client. Request for fetching client data table is going at last. So if you will click every quickly on the ```More Info``` after opening the client. It will not show anything but If you will wait for 2-3 second everything will be fine and will work great.

Closing this Issue ###

**Closed by therajanmaurya** 2017-01-23 15:39 UTC
Labels: Important
