### ISSUE TITLE
Client Name is displayed as null if Client Type is "ENTITY"

### ISSUE THREAD

**Issue by Ippezrobert** [openMF/android-client#774] opened 2017-08-24 11:22 UTC
![image](https://user-images.githubusercontent.com/13125234/29664391-14f0deb8-88d8-11e7-8a29-c26c7aca1cbe.png)

**Comment by srv-twry** [comment] 2017-12-17 05:09
@edcable Can i work on it if it's available ?

**Comment by Prem0707** [comment] 2018-01-18 23:40
@therajanmaurya I would like to work on this issue. It would be great if you can assign it to me. Thanks :)

**Comment by therajanmaurya** [comment] 2018-01-19 04:33
@Prem0707 Yeah sure go ahead and send PR.

**Comment by AkshGautam** [comment] 2018-02-03 08:39
@Prem0707 are you still working on it?

**Comment by Prem0707** [comment] 2018-02-03 08:41
Yes,I am. I am little stuck with code base.

**Comment by AkshGautam** [comment] 2018-02-09 10:54
@Prem0707 if you feel stuck you can ask for help over gitter channel.if you have stopped working on this then @tarun0 @therajanmaurya  I would like to do this.

**Comment by Prem0707** [comment] 2018-02-09 16:01
@akshGautam I am already in halfway of PR, most probably I will send it by Sunday evening. I will let you know if I wouldn't be able to resolve this issue. Thanks :)

**Comment by AkshGautam** [comment] 2018-02-09 16:15
@Prem0707 Glad to hear this. You can take your time if you are close to solving it.If you feel stuck, we can solve it together. Take your time, No hurry.

**Comment by Prem0707** [comment] 2018-02-11 18:27
@therajanmaurya @tarun0 @luckyman20 I can see some of the entries as null but i am unable to reproduce it by myself openMF/android-client#774
It would be great if can get any leads regarding that. Thanks

**Comment by AkshGautam** [comment] 2018-02-12 13:52
@tarun0 @therajanmaurya  I would like to try this task.

**Comment by Prem0707** [comment] 2018-02-12 13:52
@luckyman20 I am not able to resolve the issue inspite of spending so much time on it, @AkshGautam if you want work on it Please comment once for mentor approval. Thanks

**Comment by AkshGautam** [comment] 2018-02-12 16:29
@tarun0 @therajanmaurya  I would like to try this task.

**Closed** 2018-08-15 07:53 UTC
Labels: Important, enhancement
