### ISSUE TITLE
The keyboard hides navigation drawer

### ISSUE THREAD

**Issue by HaripriyaB** [openMF/android-client#1469] opened 2020-03-30 18:22 UTC
**Summary:** 
The keyboard hides the navigation drawer when we click on the drawer while keyboard is open

![UIbug](https://user-images.githubusercontent.com/34762451/77947271-52c3e780-72e1-11ea-9e15-db55256cc53b.gif)

**Expected behaviour:** 
Fix is to pull down the keyboard when navigation menu is opened.
**Device and Android version:** 
Android 9
Oppo A9 2020

**Comment by HaripriyaB** [comment] 2020-03-30 18:23
I've fixed this issue, PR review is pending.

**Comment by HaripriyaB** [comment] 2020-03-30 19:29
Review required...

**Comment by Grandolf49** [comment] 2020-03-30 20:28
Hi @HaripriyaB This issue has already been addressed and solved by @robustTechie #1234  Please close the issue

**Comment by robustTechie** [comment] 2020-03-31 05:03
@HaripriyaB please close this issue as this issue is duplicate of #1234

**Closed** 2020-03-31 06:53 UTC
