### ISSUE TITLE
Error Creating a client account

### ISSUE THREAD

**Issue by Siltech** [openMF/android-client#484] opened 2017-01-26 11:25 UTC
Hello, 

There is an issue when i try to create a client account through the android app. Please help me understand how i can go around this. Kindly help me with the logic to this, maybe also by removing the Current Address block.

On the save dialog, I'm getting::
# 
> "the datatable [Client Address] needs to be filled in before the current action can be completed"
![photo5787646668664055724](https://cloud.githubusercontent.com/assets/25096223/22329645/086922ec-e377-11e6-8844-26ef6a588a85.jpg)

**Comment by therajanmaurya** [comment] 2017-01-26 14:28
@Siltech Right now the app does not support. @tarun0 is working in this feature.
BTW you can create client easily without the DataTable. Do one thing remove data table attached to client.
Look this doc, how to attached and remove DataTable : https://mifosforge.jira.com/wiki/display/docs/Entity+Data+Table+Checks#suk=ff8080813fbbb4b9013fbbb6235e0008

**Comment by tarun0** [comment] 2017-01-29 05:51
@therajanmaurya Since I'm working on this already, can this issue be assigned to me?

**Comment by Siltech** [comment] 2017-01-30 09:22
That's kind of you @tarun0 . Though I'm wondering, through the code, is there a way to get around the data-table requirement. I've been trying this using the procedure given by @therajanmaurya and its not working out as it should work.

**Comment by Siltech** [comment] 2017-01-30 10:01
@therajanmaurya it your solution works. However, the client name is replicated without a unique identifier. So you may enter values for one person multiple times.

**Comment by tarun0** [comment] 2017-01-30 12:30
@Siltech Could you please elaborate the issue of replicated client names that you are facing - maybe with screenshots/gif and/or with steps to reproduce it?
If you feel that's something independent of this issue (unable to create client because of datatables), please consider making a separate issue.

Alternatively, you can discuss it on the Gitter channel as well: https://gitter.im/openMF/android-client

**Comment by therajanmaurya** [comment] 2017-02-05 13:31
@Siltech It is fixed now. You can create client offline and online.
fix in #501

**Closed by therajanmaurya** 2017-02-05 13:31 UTC
