### ISSUE TITLE
User Profile View feature 

### ISSUE THREAD

**Issue by iml-v** [openMF/android-client#837] opened 2018-02-07 17:11 UTC
**Summary:** 
There should be new feature so that the user can be able to click on the profile icon and view his profile .

**Steps to reproduce:** 

Open the app and open the Navbar and click on profile image .

**Expected behavior:** 

On clicking the profile icon there should be a fragment loaded so that user can view his/her profile .

**Observed behavior:** 

On clicking profile icon nothing happens.

**Device and Android version:** 

Android 7.0 ,API 24

![screenshot_20180207-223530 1](https://user-images.githubusercontent.com/30701209/35930365-b6e7691e-0c57-11e8-8fa3-2f402c8bf321.png)

**Comment by iml-v** [comment] 2018-02-07 17:13
@therajanmaurya @tarun0  I am working on this issue.
Any suggestion or something that you want to tell about before working?

**Comment by AkshGautam** [comment] 2018-02-12 06:17
@iml-v This issue is a duplicate of #568

**Comment by tarun0** [comment] 2018-02-12 11:36
@iml-v Follow #568 and the mockup https://github.com/openMF/Mifos-Mockups/blob/master/android-client%20-%20Mockups/Mockup-screenshots/Mifos%20User%20Profile.png

Closing this issue.

**Closed by tarun0** 2018-02-12 11:36 UTC

**Comment by iml-v** [comment] 2018-02-12 11:49
@tarun0  that issue was created a long back i have not noticed it ,sorry for inconvenience ,should i work on existing issue #568  if you assign me .
