### ISSUE TITLE
How is loan cycle calculated: https://mifosforge.jira.com/browse/MIFOSAC-81

### ISSUE THREAD

**Issue by chhavip** [openMF/android-client#138] opened 2015-10-22 18:59 UTC
As given in the bug, I have successfully displayed the loan officer name and the groups but not being able to figure out how loan cycle is calculated from the json response:
'{"id":12,"accountNo":"000000012","externalId":"40300","status":{"id":300,"code":"clientStatusType.active","value":"Active"},"subStatus":{},"active":true,"activationDate":[2013,7,16],"firstname":"chemonges","lastname":"innn","displayName":"chemonges innn","gender":{},"clientType":{},"clientClassification":{},"officeId":148,"officeName":"Mysore office","staffId":85,"staffName":"Dragon, G","timeline":{"submittedOnDate":[2013,7,16],"activatedOnDate":[2013,7,16]},"savingsAccountId":468,"groups":[{"id":1,"accountNo":"000000001","name":"safiyudeenv"},{"id":6,"accountNo":"000000006","name":"Test Communal Bank"},{"id":18,"accountNo":"000000018","name":"group01"},{"id":68,"accountNo":"000000068","name":"Bloo2"},{"id":395,"accountNo":"000000395","name":"Indatwa"},{"id":454,"accountNo":"000000454","name":"Sughosh"},{"id":473,"accountNo":"000000473","name":"werwesdf"},{"id":517,"accountNo":"000000517","name":"Large Group"}]}'

**Comment by luckyman20** [comment] 2018-03-15 13:02
@chhavip I think you can ask this question on [Gitter Channel](https://gitter.im/openMF/mifos) as this is not a bug or enhancement of the app and please close the issue

**Closed** 2023-06-27 04:01 UTC
