### ISSUE TITLE
each item takes full height of the screen 

### ISSUE THREAD

**Issue by dilpreet96** [openMF/android-client#483] opened 2017-01-26 09:10 UTC
**Summary:** 

Each list-item for ClientNameListAdapter,GroupNameListAdapter,CentersListAdapter takes the full height of the screen. Each list-item should take enough height of its content.

**Steps to reproduce:** 

Click on Clients or Groups or Centers from the Navigation Drawer. Each list-item takes full length of screen

**Expected behavior:** 

list-item should take enough height of its content .

**Observed behavior:** 

 list-item takes full length of screen

**Device and Android version:** 

Samsung on-7
Android version: 6.0.1

**Screenshots:** 
<img src="http://i.imgur.com/j34aRW3.png" style="width:100px; height:200px;">

**Comment by therajanmaurya** [comment] 2017-01-26 14:30
@dilpreet96 are you working on latest build?
Can you please test in other device and If you are getting the same issue or not?

**Comment by dilpreet96** [comment] 2017-01-26 14:52
@therajanmaurya ,Yes I am working on latest build . (Checked again by fetching from upstream/master) 
Got same result on Micromax Canvas 2 Colours ,
Android Version:4.4.2
Shall I work on it ?

**Comment by therajanmaurya** [comment] 2017-01-26 14:58
It's strange because I am working on the latest build and I can't reproduce this issue. 
My device is Moto G turbo 3 API 24

**Comment by therajanmaurya** [comment] 2017-01-26 15:01
@edcable @tarun0 @mayank-kgp Can you please confirm about this issue.

**Comment by mayank-kgp** [comment] 2017-01-26 15:06
@therajanmaurya App is working fine on my device. My device is Micromax yureka with android version 5.1.1

**Comment by therajanmaurya** [comment] 2017-01-26 16:13
@dilpreet96 Ok If you are really getting this issue, send a PR and let me look closely why this is happening.

**Comment by dilpreet96** [comment] 2017-01-26 17:18
@therajanmaurya PR sent.
<View/> in row_client_name and row_group_name where causing problem even after making the parent as wrap_content so removed the <View/> and added the isSelected() logic to linearLayout background for multiple selections.

**Comment by tarun0** [comment] 2017-01-26 18:17
I too observed this behaviour once. However, I could not replicate the issue after one or two times and it was like 1-2 months ago and never observed that again.
Tried again now with Kitkat and Marshmallow and the app works fine for me as well.

**Comment by therajanmaurya** [comment] 2017-02-19 15:33
fixed in #533 and #534

**Closed by therajanmaurya** 2017-02-19 15:33 UTC
