### ISSUE TITLE
Latest tracked path is not showing on the top of the list

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/android-client#1167] opened 2019-06-28 07:00 UTC
**Summary:** 

In the Path tracker activity, the latest tracked path is not adding on the top of the list, List must be sorted according to the latest added paths.

**Steps to reproduce:** 

Go to Path Tracker -->  Start tracking path

**Expected behavior:** 

The latest tracked path should be shown on the top.

**Observed behavior:** 

The latest tracked path is not showing on the top and it was adding on the bottom.

**Device and Android version:** 

Device: Galaxy J5 
Version: 6.1.0

**Screenshots:** 

![WhatsApp Image 2019-06-28 at 12 19 05 PM](https://user-images.githubusercontent.com/30550059/60323655-4d2b2100-99a0-11e9-8d99-46f983053a8e.jpeg)

**Comment by akatsuki619** [comment] 2019-11-05 05:27
g

**Comment by laxyapahuja** [comment] 2019-12-30 11:31
@luckyman20 this seems to be a duplicate of #565

**Comment by luckyman20** [comment] 2019-12-31 07:07
@laxyapahuja Yes, you are correct. Thanks for pointing it out.

**Closed by luckyman20** 2019-12-31 07:07 UTC
